version: '2.2'

services:
  clickhouse_server:
    container_name: clickhouse_server
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "19000:9000"
    environment:
      - discovery.type=single-node
      - nofile=262144:262144
    volumes:
      - ./data:/var/lib/clickhouse/
      - ./logs:/val/log/clickhouse-server/
      - ./import:/import/
      # - ./clickhouse-server/config.xml:/etc/clickhouse-server/config.xml
      # - ./clickhouse-server/users.xml:/etc/clickhouse-server/users.xml
      # - ./clickhouse-server/config.d/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
      # - ./clickhouse-server/usert.d:/etc/clickhouse-server/users.d/
      - ./initdb:/docker-entrypoint-initdb.d/
